# fly.toml app configuration file generated for hermes-data-service-muddy-cloud-3029 on 2024-09-12T16:43:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hermes-data-service-muddy-cloud-3029'
primary_region = 'sjc'

[build]

[env]
  PORT = '8080'

# fly.toml
[[processes]]
  name = "cron"
  command = "bun run src/cron/email/index.ts"

[[processes]]
  name = "app"
  command = "bun run src/index.ts"
  
[[services]]
  processes = ["cron"]
  [[services.ports]]
    handlers = ["http"]
    port = 8080

[[jobs]]
  name = "hourly_email_job"
  schedule = "@hourly"
  command = ["bun", "run", "src/cron/email/index.ts"]


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
