export const RECRUITMENT_KEYWORDS = [
	"application status",
	"your application",
	"your candidacy",
	"your resume",
	"your cv",
	"interview",
	"job opportunity",
	"position",
	"recruitment process",
	"hiring process",
	"thank you for applying",
	"phone screen",
	"technical interview",
	"onsite interview",
	"next round",
	"next steps",
	"offer letter",
	"job offer",
	"pleased to offer",
	"unfortunately",
	"regret to inform",
	"moved forward",
	"not moving forward",
	"decision regarding",
];

export const BLACKLIST_KEYWORDS = [
	"unsubscribe",
	"newsletter",
	"promotion",
	"sale",
	"discount",
	"marketing",
	"subscription",
	"advertisement",
	"promotional",
	"deal",
	"limited time",
	"special offer",
];

export const EMAIL_CONTEXTS = {
	JOB: "job",
	INTERVIEW: "interview",
	IRRELEVANT: "irrelevant",
	REJECTED: "rejected",
	OFFER: "offer",
	ACCEPTED: "accepted",
} as const;
